version: "4"

services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - 7077:7077
      - 8089:8080
      - 4040:4040
    volumes:
      - ../src:/src
    environment:
      SPARK_MODE: master
      SPARK_HOME: /opt/spark
      SPARK_JAVA_OPTS: "-Dspark.jars.ivy=/tmp/.ivy2"

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    ports:
      - 18081:8081
    volumes:
      - ../src:/src
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_HOME: /opt/spark
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G

networks:
  default:
    name: iot_analytics
    external: true
