CASE 
    WHEN municipality = 'Acrelândia' THEN 'BR-AC-01'
    WHEN municipality = 'Assis Brasil' THEN 'BR-AC-02'
    WHEN municipality = 'Brasiléia' THEN 'BR-AC-03'
    WHEN municipality = 'Bujari' THEN 'BR-AC-04'
    WHEN municipality = 'Capixaba' THEN 'BR-AC-05'
    WHEN municipality = 'Cruzeiro do Sul' THEN 'BR-AC-06'
    WHEN municipality = 'Epitaciolândia' THEN 'BR-AC-07'
    WHEN municipality = 'Feijó' THEN 'BR-AC-08'
    WHEN municipality = 'Jordão' THEN 'BR-AC-09'
    WHEN municipality = 'Marechal Thaumaturgo' THEN 'BR-AC-12'
    WHEN municipality = 'Mâncio Lima' THEN 'BR-AC-10'
    WHEN municipality = 'Manoel Urbano' THEN 'BR-AC-11'
    WHEN municipality = 'Plácido de Castro' THEN 'BR-AC-13'
    WHEN municipality = 'Porto Acre' THEN 'BR-AC-22'
    WHEN municipality = 'Porto Walter' THEN 'BR-AC-14'
    WHEN municipality = 'Rio Branco' THEN 'BR-AC-15'
    WHEN municipality = 'Rodrigues Alves' THEN 'BR-AC-16'
    WHEN municipality = 'Santa Rosa do Purus' THEN 'BR-AC-17'
    WHEN municipality = 'Sena Madureira' THEN 'BR-AC-19'
    WHEN municipality = 'Senador Guiomard' THEN 'BR-AC-18'
    WHEN municipality = 'Tarauacá' THEN 'BR-AC-20'
    WHEN municipality = 'Xapuri' THEN 'BR-AC-21'
    ELSE null
END