version: "4"

services:
  nifi:
    image: apache/nifi:1.24.0
    restart: unless-stopped
    container_name: nifi
    ports:
      - 8443:8443
    volumes:
      - conf:/opt/nifi/nifi-current/conf
      - data:/opt/nifi/nifi-current/data
      - logs:/opt/nifi/nifi-current/logs
      - flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
    environment:
      NIFI_WEB_HTTP_PORT: 8443

volumes:
  conf: {}
  data: {}
  logs: {}
  flowfile_repository: {}

networks:
  default:
    name: iot_analytics
    external: true
